spring:
  application:
    name: embassy-flow
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:embassy_flow}
    username: ${DB_USER:embassy}
    password: ${DB_PASSWORD:embassy_dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html